
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: zenio #SUPERUSER
  password: 123456
  host: localhost

development:
  <<: *default
  database: meu_projeto_development

test:
  <<: *default
  database: meu_projeto_test

production:
  <<: *default
  database: meu_projeto_production
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
